"""empty message

Revision ID: 437e1974b10a
Revises: 611cf00408b4
Create Date: 2023-04-02 23:37:34.954672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '437e1974b10a'
down_revision = '611cf00408b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=True))
        batch_op.drop_constraint('customer_profiles_email_number_key', type_='unique')
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.drop_column('email_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_number', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('customer_profiles_email_number_key', ['email_number'])
        batch_op.drop_column('email')

    # ### end Alembic commands ###
