"""empty message

Revision ID: adbd13df50a4
Revises: 437e1974b10a
Create Date: 2023-04-10 23:50:41.695605

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'adbd13df50a4'
down_revision = '437e1974b10a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment_schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_time', sa.DateTime(), nullable=True))
        batch_op.drop_column('endt_time')
        batch_op.drop_column('end_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment_schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('endt_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('end_time')

    # ### end Alembic commands ###
